[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.100.0"
  [[module.imports]]
    path = "github.com/tim-koko/docsy-timkoko"
    disable = false
  [[module.imports]]
    path = "github.com/acend/docsy-plus"
    disable = false

[params]
copyright = "Tim&Koko AG"
imagePrefix = "timkoko_"

enabledModule = "base timkoko"

[[Languages.en.menu.main]]
copyright = "Tim&Koko AG"
url = "https://www.tim-koko.ch"

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/acend/kubevirt-basics-training"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/tim_und_koko"

[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/tim-koko/"
