# KubeVirt Basics Training
acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: acend
      replicaCount: 2
      image:
        repository: ghcr.io/acend/kubevirt-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        secretOverride: acend-wildcard
        appname: kubevirt-basics
        domain: training.acend.ch
    - 
      name: timkoko
      replicaCount: 2
      image:
        repository: ghcr.io/acend/kubevirt-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-timkoko"
      ingress:
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        secretOverride: cert-timkoko
        appname: kubevirt-basics
        domain: training.tim-koko.ch


nameOverride: "kubevirt-basics-training"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
